# Generated by Django 5.0.1 on 2024-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourceName', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('DifficultyLevel', models.CharField(max_length=100)),
                ('CourseRating', models.FloatField()),
                ('CourseDescription', models.TextField()),
            ],
        ),
    ]
