# Generated by Django 5.0.1 on 2024-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_rename_cource_course_student_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='Skill',
            field=models.TextField(default=''),
        ),
    ]
