# Generated by Django 5.0.1 on 2024-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_alter_student_age_alter_student_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
